## 4.1

In [2]:
import numpy as np

### (a)

In [3]:
A = np.array([[3, 0], [0, -2]])
A

array([[ 3,  0],
       [ 0, -2]])

In [5]:
U, s, Vh = np.linalg.svd(A)

In [6]:
U

array([[1., 0.],
       [0., 1.]])

In [8]:
s

array([3., 2.])

In [9]:
Vh

array([[ 1.,  0.],
       [-0., -1.]])

In [13]:
assert np.allclose(U @ np.diag(s) @ Vh, A)

In [10]:
I = np.array([[1, 0], [0, 1]])
I

array([[1, 0],
       [0, 1]])

$det(A - \lambda I) = 0$

$(3-\lambda)(-2 - \lambda) = 0$

Therefore eigenvalues are 3 and -2

\begin{bmatrix}
3x_1^2+24x_1^5+12x_1^2x_3^2 & 4x_2& 5 + 8x_1^3x_3 + 4x_3^3 \\
12x_1^2 & 0 & 4x_3
\end{bmatrix}